### ISSUE TITLE
Lit element linting

### ISSUE THREAD

**Issue by jennasalau** [DeloitteDigitalAPAC/rhythm-ui#16]
We should look at implementing

https://www.npmjs.com/package/eslint-plugin-lit

Into the components linting settings:

```
| -- components
      |-- .eslint << Extended with plugin in here for this folder and its children
|-- .eslint
|-- package.json << Dep added here though
```

**Comment by terencejeong** [comment]
I've got this linter going, are we happy to extend to the "plugin:lit/recommended" as well?
