### ISSUE TITLE
Configuration options for web components

### ISSUE THREAD

**Issue by ricominten** [DeloitteDigitalAPAC/rhythm-ui#50]
Given the option to configure `rui-breadcrumbs` with either a data object or with child elements, is it worth keeping/supporting both?

I understand that there is a potential benefit in supporting both, however this also comes with extra complexity and weight in the codebase that is not strictly required (though admitted it's not much).

Traditionally there have not been a lot of use cases where a FED would _set_ any JSON in the DOM. As far as use cases, we consume it as a data-object being set in the DOM or as data received from an API and map it out to DOM elements.

As such the value supporting this would be mostly to support a CMS configuration, where we provide a potentially easier configuration of the breadcrumbs component. There is no guarantee however that said CMS will provide the correct JSON structure natively, still requiring either modification or mapping this out with the child components.

**Comment by jennasalau** [comment]
I'm not actually opposed to this idea.

I agree that the added code is not much for breadcrumbs but this could get worse with more complex components.

Architecturally it would make more sense to abstract that logic into a layer above.. something like `rui-breadcrumbs-data-provider`.

Also looking at the documentation, it would make it simpler too.

**Comment by ricominten** [comment]
Decision is to minimise usage of JSON and move where possible to data-providers
